# Header
menu:
  首页: /
  文章: /archives
  AboutMe: /about
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- tagcloud
- ad
#- category
#- tag
#- archive
#- recent_posts

# Miscellaneous
google_analytics:
favicon: /css/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: